### PR TITLE
Bugfix 87 fixing lambdas for keycloak

### LINKED ISSUE #87: Fixing lambdas for Keycloak

### PR DESCRIPTION
**Pull request by dalju005-xamk**
Fixing both lambdas to return same type of information. Small changes to api also.
User model is in new path, because folder structure is going to change in PR: feature-84

### CODE REVIEW

**Review by naStipe — APPROVED** [review]

File: src/database/services/keycloak-api-service.ts [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
 import fetch from "node-fetch";
 
 /**
  * Interface for a KeycloakApiService.
  */
 export interface KeycloakApiService {
   getUsers: () => Promise<User[]>;
-  findUser: (id: string) => Promise<User[]>;
+  findUser: (id: string) => Promise<User>;
 }
```
Comment (Hanhz2707) [inline src/database/services/keycloak-api-service.ts:11]: Maybe we can won't need this empty space as Josh reviewed our old PR and commented about this

**Review by Hanhz2707 — APPROVED** [review]

File: src/functions/keycloak/find-user/handler.ts [hunk 2]
```diff
@@ -1,19 +1,10 @@
 import type { APIGatewayProxyEvent, APIGatewayProxyHandler } from "aws-lambda";
 import { CreateKeycloakApiService } from "src/database/services/keycloak-api-service";
 import { middyfy } from "src/libs/lambda";
-
+import type { User } from "src/types/keycloak/user";
 /**
- * Response schema for lambda
+ * FIXME: At this moment in KeyCloak its called: severa-user-id (string), in here its severaGuid (string);
```
Comment (Jdallos) [inline src/functions/keycloak/find-user/handler.ts]: If this relates to the severaGuid attribute in filteredUser then I'd suggest putting the comment directly above the attribute. However if the attribute name is defined in the User type, then I'd suggest putting this comment there- unless there is a reason not to?

File: src/functions/keycloak/find-user/handler.ts [hunk 3]
```diff
@@ -33,11 +24,27 @@ const findUserHandler: APIGatewayProxyHandler = async (
       throw new Error("Missing or invalid path parameter: id");
     }
 
-    const userById = await api.findUser(queryStringParameters.id);
+    const userById: User = await api.findUser(queryStringParameters.id);
```
Comment (Jdallos) [inline src/functions/keycloak/find-user/handler.ts]: I don't think this needs explicitly typing as User

File: src/functions/keycloak/find-user/handler.ts [hunk 4]
```diff
@@ -33,11 +24,27 @@ const findUserHandler: APIGatewayProxyHandler = async (
...
+    }
+    const filteredUser: User = {
+      id: userById.id,
+      firstName: userById.firstName,
+      lastName: userById.lastName,
+      email: userById.email,
+      isActive: userById.isActive,
+      severaGuid: userById.severaGuid,
+      forecastId: userById.forecastId
+    };
```
Comment (Jdallos) [inline src/functions/keycloak/find-user/handler.ts]: I'm a bit confused, why are we filtering user here? Is it because the response from the api.findUser is not actually of User type? In which case the response type should be updated to reflect what is actually returned from the request.

File: src/database/services/keycloak-api-service.ts [hunk 5]
```diff
@@ -45,7 +45,7 @@ export const CreateKeycloakApiService = (): KeycloakApiService => {
      * @param id string
      * @returns user by Id
      */
-    findUser: async (id: string): Promise<User[]> => {
+    findUser: async (id: string): Promise<User> => {
```
Comment (Jdallos) [inline src/database/services/keycloak-api-service.ts]: Is this actually returning something of type User?

File: src/functions/keycloak/list-users/handler.ts [hunk 6]
```diff
@@ -1,22 +1,10 @@
...
-import {
-  CreateKeycloakApiService,
-  type KeycloakApiService,
-} from "src/database/services/keycloak-api-service";
-
+import { CreateKeycloakApiService } from "src/database/services/keycloak-api-service";
+import type { User } from "src/types/keycloak/user";
 /**
- * Response schema for lambda
+ * FIXME: At this moment in KeyCloak its called: severa-user-id (string);
```
Comment (Jdallos) [inline src/functions/keycloak/list-users/handler.ts]: Same as in previous file, lets leave a single comment explaining this, perhaps in the User type definition

File: src/functions/keycloak/list-users/handler.ts [hunk 7]
```diff
@@ -27,22 +15,24 @@ const listUsersHandler: APIGatewayProxyHandler = async () => {
 
     const users = await api.getUsers();
```
Comment (Jdallos) [inline src/functions/keycloak/list-users/handler.ts:12]: TS thinks this is of type User form the getUsers method return type definition. But becuase you are doig "filteredUsers" I suspect its not. See previous comment in other file, but this should be typed correctly so it's clear why we are filtering users.

Also I would change the naming, I think in this case we would usually call it mappedUsers. 

If it seems I've misunderstood something lets discuss further

File: src/functions/keycloak/list-users/handler.ts [hunk 8]
```diff
@@ -27,22 +15,24 @@ const listUsersHandler: APIGatewayProxyHandler = async () => {
...
 
-    const mappedUsers: Response[] = users.map((user) => {
-      const responseUser: Response = {
+    const filteredUsers: User[] = [];
+
+    for (let i = 0; i < users.length; i++) {
```
Comment (Jdallos) [inline src/functions/keycloak/list-users/handler.ts]: This should be done with a map, unless there is a good reason not to?

**Review by Jdallos — CHANGES_REQUESTED** [review]

File: src/functions/keycloak/list-users/handler.ts (hunk 8 above)
Comment (dalju005-xamk) [reply src/functions/keycloak/list-users/handler.ts]: Sure, this was note from Ilmo to avoid mapping. There was something with SonarCloud giving negative feedback about mapping.

File: src/database/services/keycloak-api-service.ts [hunk 9]
```diff
@@ -1,12 +1,37 @@
-import type { User } from "../../types/keycloak/user";
 import fetch from "node-fetch";
 
+/**
+ * Interface for a KeycloakProfile. 
+ * 
+ * FIXME: This is from node_modules/keycloak-js/lib/keycloak.d.ts
+ *  This a temporary solution to avoid the error: "Cannot find module 'keycloak-js'"  
+ */
+
```
Comment (Jdallos) [inline src/database/services/keycloak-api-service.ts]:
```suggestion
```

File: src/database/services/keycloak-api-service.ts [hunk 10]
```diff
@@ -1,12 +1,37 @@
...
+export interface KeycloakProfile {
+	id?: string;
```
Comment (Jdallos) [inline src/database/services/keycloak-api-service.ts]: Fix indentation

File: src/database/services/keycloak-api-service.ts [hunk 11]
```diff
@@ -1,12 +1,37 @@
...
+	enabled?: boolean;
+	emailVerified?: boolean;
+	totp?: boolean;
+	createdTimestamp?: number;
+	attributes?: Record<string, unknown>;
+}
+/**
+ * Custom Interface for a user in keycloak functions with severaGuid added.
+ */
+
```
Comment (Jdallos) [inline src/database/services/keycloak-api-service.ts]: There is no need for a line break between the Docs and the thing that is being documented. I keep seeing this

Comment (Jdallos) [inline src/database/services/keycloak-api-service.ts]:
```suggestion
```

File: src/database/services/keycloak-api-service.ts [hunk 12]
```diff
@@ -36,7 +61,11 @@ export const CreateKeycloakApiService = (): KeycloakApiService => {
         );
       }
 
-      return response.json();
+      const users: KeycloakProfile[] = await response.json();
+      return users.map((user) => ({
+        ...user,
+        severaGuid: (user as CustomKeycloakProfile).severaGuid ?? "Users SeveraGuid not found in Keycloak",
```
Comment (Jdallos) [inline src/database/services/keycloak-api-service.ts]: We don't want to set the severaGuid as a error message string. Let's set it as undefined or null- you decide.
Also Stepan suggested last week we change all references to Guid to Id and I tend to agree. Lets do this here unless you disagree?

File: src/database/services/keycloak-api-service.ts [hunk 13]
```diff
@@ -60,7 +89,11 @@ export const CreateKeycloakApiService = (): KeycloakApiService => {
         throw new Error(`Failed to find user with id: ${id}`);
       }
 
-      return response.json();
+      const user: KeycloakProfile = await response.json();
+      return {
+        ...user,
+        severaGuid: (user as CustomKeycloakProfile).severaGuid ?? "Users SeveraGuid not found in Keycloak",
```
Comment (Jdallos) [inline src/database/services/keycloak-api-service.ts]: Undefined or null same as above, also rename

File: src/functions/keycloak/find-user/handler.ts [hunk 14]
```diff
@@ -24,27 +20,17 @@ const findUserHandler: APIGatewayProxyHandler = async (
       throw new Error("Missing or invalid path parameter: id");
     }
 
-    const userById: User = await api.findUser(queryStringParameters.id);
+    const userById = await api.findUser(queryStringParameters.id);
```
Comment (Jdallos) [inline src/functions/keycloak/find-user/handler.ts:22]: There is an unnecessary line break between Docs and findUserHandler

File: src/functions/keycloak/list-users/handler.ts [hunk 15]
```diff
@@ -1,10 +1,7 @@
 import { middyfy } from "@libs/lambda";
 import type { APIGatewayProxyHandler } from "aws-lambda";
 import { CreateKeycloakApiService } from "src/database/services/keycloak-api-service";
-import type { User } from "src/types/keycloak/user";
-/**
- * FIXME: At this moment in KeyCloak its called: severa-user-id (string);
- */
+
```
Comment (Jdallos) [inline src/functions/keycloak/list-users/handler.ts:4]: No need for a double line break here

File: src/types/keycloak/user.ts [hunk 16]
```diff
@@ -9,4 +9,7 @@ export interface User {
     isActive: boolean;
     severaGuid: string;
     forecastId: number;
-}
\ No newline at end of file
+}
+/**
+ * FIXME: At this moment in KeyCloak its called: severa-user-id (string), in here its severaGuid (string);
```
Comment (Jdallos) [inline src/types/keycloak/user.ts]: Lets rename to severaId and remove this comment

**Review by Jdallos — CHANGES_REQUESTED** [review]

File: src/database/services/keycloak-api-service.ts (hunk 12 above)
Comment (dalju005-xamk) [reply src/database/services/keycloak-api-service.ts]: Stepan success that we use severaUserGuid. I think that would be fine.

File: src/database/services/keycloak-api-service.ts [hunk 17]
```diff
@@ -6,25 +6,23 @@ import fetch from "node-fetch";
...
+  attributes?: Record<string, unknown>;
 }
 /**
- * Custom Interface for a user in keycloak functions with severaGuid added.
+ * Custom Interface for a user in keycloak functions with severaUserGuid added.
  */
-
 export interface CustomKeycloakProfile extends KeycloakProfile {
-  severaGuid: string;
+  severaUserGuid: string;
```
Comment (Jdallos) [inline src/database/services/keycloak-api-service.ts]: I said in a previous comment, lets rename all Guid references to Id

File: src/types/keycloak/user.ts [hunk 18]
```diff
@@ -7,9 +7,6 @@ export interface User {
     lastName: string;
     email: string;
     isActive: boolean;
-    severaGuid: string;
+    severaUserGuid: string;
```
Comment (Jdallos) [inline src/types/keycloak/user.ts]: Rename

**Review by Jdallos — CHANGES_REQUESTED** [review]

**Review by Jdallos — APPROVED** [review]
