### PR TITLE
Fixed endpoint and draft

### LINKED ISSUE #127: Typos in endpoints for vacation requests
Fixing typos in endpoints for vacation requests and handling "draft" attribute

### PR DESCRIPTION
**Pull request by naStipe**

### CODE REVIEW

**Review by dalju005-xamk — APPROVED** [review]

File: src/functions/vacation-request/create-vacation-request/handler.ts [hunk 1]
```diff
@@ -18,7 +18,19 @@ export const createVacationRequestHandler: ValidatedEventAPIGatewayProxyEvent<ty
...
+    days,
+    draft,
+    endDate,
+    message,
+    startDate,
+    status,
+    type,
+    updatedAt,
+    userId
+  }} = event;
```
Comment (McDuuck) [inline src/functions/vacation-request/create-vacation-request/handler.ts:34]: Could this be:
`const { body } = event
const {
    createdAt,
    createdBy,
    days,
    draft,
    endDate,
    message,
    startDate,
    status,
    type,
    updatedAt,
    userId
} = body;`

Like in some of the other projects? just a thought.

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 2]
```diff
@@ -9,21 +9,20 @@ import type vacationRequestSchema from "src/schema/vacationRequest";
...
-    createdBy,
-    createdAt,
+    startDate,
+    status,
+    type,
     updatedAt,
-  } = event.body;
+    userId
+  }} = event;
+  const id = pathParameters?.id;
```
Comment (McDuuck) [inline src/functions/vacation-request/update-vacation-request/handler.ts:27]: Same with here

**Review by McDuuck — APPROVED** [review]

**Review by Jdallos — APPROVED** [review]
