### PR TITLE
Ensure the validation check is there before database updates.

### LINKED ISSUE #320: Database Updated Before vacation Days validation
The vacation request was being persisted to database before validating whether the user has sufficient vacation days. If validation fails after database update, then vacation request would be on Approved state in database but users vacation days in key cloak will not be deducted creating data inconsistency. 

Also when a user edits already approved vacation request it never restores /add back the vacation days of the OLD dates. 
So when a vacation request is rejected or cancelled after being approved, vacation days should be restored to the user.

### PR DESCRIPTION
**Pull request by Dshad-Anon**
Validation works for this. The user cannot create requests with more days than available.

### CODE REVIEW

File: src/libs/vacation-utils.ts [hunk 1]
```diff
@@ -88,32 +88,47 @@ export const splitVacationDaysByYear = (
...
- * @returns A promise that resolves when the user's vacation days have been updated.
+ * @returns True if user has enough days, false otherwise.
  */
-export const updateRemainingVacationDays = async (
+export const validateVacationDays = async (
   userId: string,
-  daysToSubtract: number,
-  status: string,
+  daysNeeded: number,
   year: string
```
[the remark this answers is not in the document]
Comment (Dshad-Anon) [reply src/libs/vacation-utils.ts:101]: Its not allowed in frontend to pass negative value. That will ensure its always positive number.

File: src/libs/vacation-utils.ts [hunk 2]
```diff
@@ -88,32 +88,47 @@ export const splitVacationDaysByYear = (
...
+/**
+ * Helper function to deductVacationDays - modifies Keycloak to deduct vacation days.
+ * @param userId - The ID of the user whose vacation days are being deducted.
+ * @param daysToDeduct - The number of vacation days to deduct.
+ * @param year - The year for which the vacation days are being deducted.
+ */
+export const deductVacationDays = async (
+  userId: string,
+  daysToDeduct: number,
+  year: string
```
[the remark this answers is not in the document]
Comment (Dshad-Anon) [reply src/libs/vacation-utils.ts:122]: Always postive number is allowed to be requested from frontend so leaving it.

**Review by jessesillman — APPROVED** [review]

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 3]
```diff
@@ -126,6 +117,57 @@ const updateVacationRequestHandler: ValidatedEventAPIGatewayProxyEvent<
...
+      currentStatus !== VacationRequestStatuses.Approved
+    ) {
+      const updatedVacationRequest =
+        await vacationRequestService.updateVacationRequest(vacationRequestUpdates);
+
+      await returnVacationDaysForRejection(
+        userId,
+        existingVacationRequest.startDate,
+        existingVacationRequest.endDate,
+        contractedWeek
```
[the remark this answers is not in the document]
Comment (Dshad-Anon) [reply src/functions/vacation-request/update-vacation-request/handler.ts]: user cannot change the date and status at the same time in the frontend which resolves the speculation of making inconsitency.

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 4]
```diff
@@ -126,6 +117,57 @@ const updateVacationRequestHandler: ValidatedEventAPIGatewayProxyEvent<
...
+      );
```
[the remark this answers is not in the document]
Comment (Dshad-Anon) [reply src/functions/vacation-request/update-vacation-request/handler.ts]: The new logic should look after this inconsitency.

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 5]
```diff
@@ -126,6 +117,84 @@ const updateVacationRequestHandler: ValidatedEventAPIGatewayProxyEvent<
...
       });
     }
+  };
+
+  try {
+    /**
+     * Handles vacation request approval flow.
+     * Deducts vacation days from user's balance before updating the database.
+     * Implements compensating transaction: if database update fails, vacation days are returned.
+     */
```
Comment (JuusoHeikkinen02) [inline src/functions/vacation-request/update-vacation-request/handler.ts]: remove tsdoc from here if you want to comment the workflow use //

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 6]
```diff
@@ -126,6 +117,84 @@ const updateVacationRequestHandler: ValidatedEventAPIGatewayProxyEvent<
...
+        await returnVacationDaysForRejection(userId, startDate, endDate, contractedWeek);
+        throw dbError;
+      }
+    }
+
+    /**
+     * Handles vacation request rejection/cancellation flow.
+     * Updates database status before returning vacation days to user's balance.
+     * If returning days fails, logs error but considers operation successful as status change takes priority.
+     */
```
Comment (JuusoHeikkinen02) [inline src/functions/vacation-request/update-vacation-request/handler.ts]: I guess same here

**Review by JuusoHeikkinen02 — APPROVED** [review]

File: src/functions/vacation-request/update-vacation-request/handler.ts (hunk 5 above)
Comment (Dshad-Anon) [reply src/functions/vacation-request/update-vacation-request/handler.ts]: new commit makes the new function and use of tsdocs

File: src/functions/vacation-request/create-vacation-request/handler.ts [hunk 7]
```diff
@@ -68,6 +68,21 @@ export const createVacationRequestHandler: ValidatedEventAPIGatewayProxyEvent<
...
 
   try {
+    const contractedWeek = await getContractedWeek(userId);
+    const daysByYear = splitVacationDaysByYear(startDate, endDate, contractedWeek);
+
+    for (const [year, daysInYear] of Object.entries(daysByYear)) {
+      const hasEnoughDays = await validateVacationDays(userId, daysInYear, year);
+      if (!hasEnoughDays) {
+        return {
+          statusCode: 400,
```
Comment (Jdallos) [inline src/functions/vacation-request/create-vacation-request/handler.ts]: 409 might be more appropriate, up to you

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 8]
```diff
@@ -3,17 +3,94 @@ import { middyfy } from "@libs/lambda";
...
 } from "src/libs/vacation-utils";
 import {
   notifyAdminsVacationSubmittedAll,
   notifyUserVacationStatusUpdatedAll
 } from "src/notifications/vacation-notifications";
 import type vacationRequestSchema from "src/schema/vacationRequest";
 
+/**
+ * Handles vacation request approval with compensating transaction.
+ */
```
Comment (Jdallos) [inline src/functions/vacation-request/update-vacation-request/handler.ts:29]: Include param docs

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 9]
```diff
@@ -3,17 +3,94 @@ import { middyfy } from "@libs/lambda";
...
+const handleApproval = async (
```
Comment (Jdallos) [inline src/functions/vacation-request/update-vacation-request/handler.ts:30]: HandleApproval and handleRejection should be moved into a utils (utils/vacations?) file so we keep this handler file free for just the handler. Unless there is some strong reason for them to be here?

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 10]
```diff
@@ -3,17 +3,94 @@ import { middyfy } from "@libs/lambda";
...
+  validateVacationApproval
 } from "src/libs/vacation-utils";
 import {
   notifyAdminsVacationSubmittedAll,
   notifyUserVacationStatusUpdatedAll
 } from "src/notifications/vacation-notifications";
 import type vacationRequestSchema from "src/schema/vacationRequest";
 
+/**
+ * Handles vacation request approval with compensating transaction.
```
Comment (Jdallos) [inline src/functions/vacation-request/update-vacation-request/handler.ts]: This description could be improved. e.g. verifies user has sufficient vacation days and deducts them

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 11]
```diff
@@ -3,17 +3,94 @@ import { middyfy } from "@libs/lambda";
...
+  await deductVacationDaysForApproval(userId, startDate, endDate, contractedWeek);
+
+  try {
+    const updatedVacationRequest =
+      await vacationRequestService.updateVacationRequest(vacationRequestUpdates);
+    await sendNotifications();
+
+    return {
+      statusCode: 200,
+      body: JSON.stringify(updatedVacationRequest as unknown as VacationRequest)
```
Comment (Jdallos) [inline src/functions/vacation-request/update-vacation-request/handler.ts:55]: Can this casting as unknown be done in a better way, why is there such a mismatch between the types that this is needed? Could be further work

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 12]
```diff
@@ -3,17 +3,94 @@ import { middyfy } from "@libs/lambda";
...
+    };
+  } catch (dbError) {
```
Comment (Jdallos) [inline src/functions/vacation-request/update-vacation-request/handler.ts:57]: typically just error for the param name here is best

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 13]
```diff
@@ -3,17 +3,94 @@ import { middyfy } from "@libs/lambda";
...
+    console.error("Database update failed, rolling back vacation day deduction", dbError);
+    await returnVacationDaysForRejection(userId, startDate, endDate, contractedWeek);
+    throw dbError;
+  }
+};
+
+/**
+ * Handles vacation request rejection/cancellation.
+ */
```
Comment (Jdallos) [inline src/functions/vacation-request/update-vacation-request/handler.ts:66]: Param docs and improve descripition

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 14]
```diff
@@ -3,17 +3,94 @@ import { middyfy } from "@libs/lambda";
...
+      userId,
+      existingStartDate,
+      existingEndDate,
+      contractedWeek
+    );
+    await sendNotifications();
+
+    return {
+      statusCode: 200,
+      body: JSON.stringify(updatedVacationRequest as unknown as VacationRequest)
```
Comment (Jdallos) [inline src/functions/vacation-request/update-vacation-request/handler.ts:89]: Same as previous comment, can we improve typing so this as unknown casting is not needed

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 15]
```diff
@@ -3,17 +3,94 @@ import { middyfy } from "@libs/lambda";
...
+    };
+  } catch (keycloakError) {
+    console.error("Failed to return vacation days after status change.", keycloakError);
+
+    return {
+      statusCode: 200,
+      body: JSON.stringify(updatedVacationRequest as unknown as VacationRequest)
```
Comment (Jdallos) [inline src/functions/vacation-request/update-vacation-request/handler.ts:96]: As above

File: src/functions/vacation-request/update-vacation-request/handler.ts [hunk 16]
```diff
@@ -3,17 +3,94 @@ import { middyfy } from "@libs/lambda";
...
+      existingEndDate,
+      contractedWeek
+    );
+    await sendNotifications();
+
+    return {
+      statusCode: 200,
+      body: JSON.stringify(updatedVacationRequest as unknown as VacationRequest)
+    };
+  } catch (keycloakError) {
```
Comment (Jdallos) [inline src/functions/vacation-request/update-vacation-request/handler.ts]:
```suggestion
  } catch (error) {
```

File: src/libs/vacation-utils.ts [hunk 17]
```diff
@@ -126,10 +141,41 @@ export const updateRemainingVacationDays = async (
   }
 
   user.unspentVacationDaysByYear = [...new Set(updatedUnspent)];
-  if (status === "APPROVED") {
-    await keycloakApiService.updateUserAttributes(userId, user);
+  await keycloakApiService.updateUserAttributes(userId, user);
+};
+
+/**
+ * Returns vacation days to Keycloak (adds them back).
```
Comment (Jdallos) [inline src/libs/vacation-utils.ts]:
```suggestion
 * Returns vacation days to Keycloak user (adds them back).
```

File: src/libs/vacation-utils.ts [hunk 18]
```diff
@@ -88,32 +88,47 @@ export const splitVacationDaysByYear = (
...
 
   const unspentVacationDaysByYear = user.unspentVacationDaysByYear || [];
+  const currentEntry = unspentVacationDaysByYear.find((s) => s.startsWith(`${year}:`));
+  const currentValue = currentEntry ? Number(currentEntry.split(":")[1]) : 0;
+
+  return currentValue >= daysNeeded;
+};
 
+/**
+ * Low-level helper that directly modifies Keycloak vacation day balances.
```
Comment (Jdallos) [inline src/libs/vacation-utils.ts]:
```suggestion
 * Deducts vacation days from keycloak user
```

File: src/libs/vacation-utils.ts [hunk 19]
```diff
@@ -126,10 +141,41 @@ export const updateRemainingVacationDays = async (
...
+
+  const unspentVacationDaysByYear = user.unspentVacationDaysByYear || [];
+  const currentEntry = unspentVacationDaysByYear.find((s) => s.startsWith(`${year}:`));
+  const currentValue = currentEntry ? Number(currentEntry.split(":")[1]) : 0;
+
+  const newRemainingDays = currentValue + daysToReturn;
+  const formattedValue = `${year}:${String(newRemainingDays).padStart(3, "0")}`;
+
+  const updatedUnspent = [...unspentVacationDaysByYear];
+  const existingIndex = updatedUnspent.findIndex((s) => s.startsWith(`${year}:`));
```
Comment (Jdallos) [inline src/libs/vacation-utils.ts]: Improving the name here makes the conditions below clearer- its the existing index of what.
e.g.
yearsUnspentVacationDays

Maybe

**Review by Jdallos — APPROVED** [review]

File: src/functions/vacation-request/create-vacation-request/handler.ts (hunk 7 above)
Comment (Dshad-Anon) [reply src/functions/vacation-request/create-vacation-request/handler.ts]: made the suggested error code 409.

File: src/functions/vacation-request/update-vacation-request/handler.ts (hunk 9 above)
Comment (Dshad-Anon) [reply src/functions/vacation-request/update-vacation-request/handler.ts:30]: This function has database layer dependency and some HTTP responses,so I keep them in here and it also has sendNotificatoin which is tied to this handler sending notification. VacationUtil consist of vacationDays calculation so making it clear over there.

File: src/functions/vacation-request/update-vacation-request/handler.ts (hunk 11 above)
Comment (Dshad-Anon) [reply src/functions/vacation-request/update-vacation-request/handler.ts:55]: The type mismach is that the database model stores dates as string for dynamoDB while OpenAPI model expects Date objects. So double casting throuh unknown was used first to erase to unknown then applying target type.

File: src/libs/vacation-utils.ts (hunk 19 above)
Comment (Dshad-Anon) [reply src/libs/vacation-utils.ts]: made the changes.

File: src/functions/vacation-request/update-vacation-request/handler.ts (hunk 11 above)
Comment (Jdallos) [reply src/functions/vacation-request/update-vacation-request/handler.ts:55]: Then this works as a temporary fix but further work could be to resolve this type difference. I'd suggest looking into creating a VacationDTO type with some dtoToEntity and entityToDto methods to create a mapping layer allow handling of the type difference.
This is the correct way to handle type differences between API spec and DB.
I'll create a trello card, self assign if you want this task.

File: src/functions/vacation-request/update-vacation-request/handler.ts (hunk 9 above)
Comment (Jdallos) [reply src/functions/vacation-request/update-vacation-request/handler.ts:30]: Fine for now, this handler could be starting to get bloated and may benefit from a refactor, moving these and the notification functions into th eservice perhaps?
Again a potential future task in the trello
